const data = {
    nodes: [
        { id: "node0", label: "0" },
        { id: "node1", label: "1" },
        { id: "node2", label: "2" },
        { id: "node3", label: "3" },
        { id: "node4", label: "4" },
        { id: "node5", label: "5" },
        { id: "node6", label: "6" },
        { id: "node7", label: "7" },
        { id: "node8", label: "8" },
        { id: "node9", label: "9" },
        { id: "node10", label: "10" },
        { id: "node11", label: "11" },
        { id: "node12", label: "12" },
        { id: "node13", label: "13" },
        { id: "node14", label: "14" },
        { id: "node15", label: "15" },
        { id: "node16", label: "16" },
        { id: "node17", label: "17" },
    ],
    edges: [
        { source: "node0", target: "node1" },
        { source: "node0", target: "node2" },
        { source: "node0", target: "node3" },
        { source: "node0", target: "node4" },
        { source: "node0", target: "node5" },
        { source: "node1", target: "node6" },
        { source: "node1", target: "node7" },
        { source: "node2", target: "node8" },
        { source: "node2", target: "node9" },
        { source: "node2", target: "node10" },
        { source: "node2", target: "node11" },
        { source: "node2", target: "node12" },
        { source: "node2", target: "node13" },
        { source: "node3", target: "node14" },
        { source: "node3", target: "node15" },
        { source: "node3", target: "node16" },
        { source: "node9", target: "node17" },
        { source: "node9", target: "node10" },
        { source: "node10", target: "node9" },
        { source: "node10", target: "node2" },
    ],
};

export default data;
